# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImgurUploader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ImgurUploader
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'


  target 'ImgurUploaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ImgurUploader-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ImgurUploader-tvOS

  target 'ImgurUploader-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
